### ISSUE TITLE
Openelb负载均衡策略

### ISSUE THREAD

**Issue by pangfd** [kubesphere/openelb#213]
请教一下，怎么设置Openelb的负载策略呢，比如基于IP、轮训、权重？不然在做灰度测试或者分流的时候没法做

**Comment by FeynmanZhou** [comment]
> 请教一下，怎么设置Openelb的负载策略呢，比如基于IP、轮训、权重？不然在做灰度测试或者分流的时候没法做

IMO, this is not the goal for OpenELB, you can take a look at the definition and documents of OpenELB. You may need to consider Nginx or HAproxy to implement these strategies.
